repos:
  # Code formatting and linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [-r, -f, json]
        files: ^src/

  # Type checking  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^src/
        args: [--config-file=pyproject.toml]
        additional_dependencies: [types-PyYAML]

  # Version management
  - repo: local
    hooks:
      - id: version-tagging
        name: Version tagging and changelog update
        entry: .github/hooks/version-hook.sh
        language: script
        pass_filenames: false
        stages: [pre-push]  # Run on push, not commit
        always_run: true
        verbose: true
