scheduler:
  cleanup_interval: 900
  data_store:
    type: sqlalchemy
    #uri: sqlite+aiosqlite:///scheduler.db
    uri: postgresql+asyncpg://postgres:postgres@localhost:5432/flowerpower
  event_broker:
    type: mqtt
    host: localhost
    port: 1883
  max_concurrent_jobs: 100
tracker:
  api_key: null
  api_url: http://localhost:8241
  ui_url: http://localhost:8242
  username: null
