name: hello-world
open_telemetry:
  host: localhost
  port: 6381
tracker:
  api_key: null
  api_url: http://localhost:8241
  ui_url: http://localhost:8242
  username: null
worker:
  cleanup_interval: 900
  data_store:
    type: sqlalchemy
    uri: sqlite+aiosqlite:///flowerpower.db
    #uri: postgresql+asyncpg://postgres:password@localhost/flowerpower
  event_broker:
    type: redis
    uri: redis://localhost:6379
  max_concurrent_jobs: 100
