name: hello-world
open_telemetry:
  host: localhost
  port: 6381
scheduler:
  cleanup_interval: 900
  data_store:
    type: sqlalchemy
    uri: sqlite+aiosqlite:///flowerpower.db
    #uri: postgresql+asyncpg://postgres:postgres@localhost:5432/flowerpower
  event_broker:
    host: localhost
    port: 1883
    type: mqtt
  max_concurrent_jobs: 100
tracker:
  api_key: null
  api_url: http://localhost:8241
  ui_url: http://localhost:8242
  username: null
