name: hello-world
worker:
  type: apscheduler
  backend:
    data_store:
      type: postgresql
      uri: null
      username: postgres
      password: null
      host: localhost
      port: 5432
      database: null
      ssl: false
      cert_file: null
      key_file: null
      ca_file: null
      verify_ssl: false
      schema: flowerpower
    event_broker:
      type: null
      uri: null
      username: null
      password: null
      host: null
      port: null
      database: null
      ssl: false
      cert_file: null
      key_file: null
      ca_file: null
      verify_ssl: false
      from_ds_sqla: true
    cleanup_interval: 300
    max_concurrent_jobs: 10
    default_job_executor: threadpool
    num_workers: null
tracker:
  username: null
  api_url: http://localhost:8241
  ui_url: http://localhost:8242
  api_key: null
  verify: false
open_telemetry:
  host: localhost
  port: 6831
