name: hello-world
worker:
  type: rq
  backend:
    type: null
    uri: null
    username: null
    password: null
    host: null
    port: null
    database: null
    ssl: false
    ssl_cert: null
    ssl_key: null
    ssl_ca: 123
    verify_ssl: false
    queues:
    - default
tracker:
  username: user@flowerpower.de
  api_url: http://localhost:8241
  ui_url: https://localhost:8242
  api_key: null
  verify: false
open_telemetry:
  host: localhost
  port: 6381
