scheduler:
  cleanup_interval: 900
  data_store:
    type: sqlalchemy
    uri: sqlite+aiosqlite:///scheduler.db
  event_broker: {}
  max_concurrent_jobs: 100
tracker:
  api_key: null
  api_url: http://localhost:8241
  ui_url: http://localhost:8242
  username: null
