name: hello-world
adapter:
  hamilton_tracker:
    username: null
    api_url: http://localhost:8241
    ui_url: http://localhost:8242
    api_key: null
    verify: false
  mlflow:
    tracking_uri: null
    registry_uri: null
    artifact_location: null
  ray:
    ray_init_config: null
    shutdown_ray_on_completion: false
  opentelemetry:
    host: localhost
    port: 6831
