version: "3.8"
services:
  jupytercode:
    build: 
      context: .
      args:
        - CODE_VERSION=4.92.1
        - PLATFORM=arm64
    image: jupytercode:latest
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - 8888:8888
    volumes:
      - jupytercode:/home/jovyan
  #
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio1234
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  
  # mqtt:
  #   image: eclipse-mosquitto
  #   volumes:
  #     - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #   ports:
  #     - 1883:1883
  #   command: mosquitto -c /mosquitto/config/mosquitto.conf
  
  mqtt:
    image: emqx/nanomq
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883

  redis:
    image: valkey/valkey
    ports:
      - 6379:6379

  # dragonfly:
  #   image: docker.dragonflydb.io/dragonflydb/dragonfly
  #   network_mode: host
  #   ulimits:
  #     memlock: -1
  #   ports:
  #     - 6379:6379
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  nodered:
    image: nodered/node-red
    volumes:
      - nodered:/data
    ports: 
      - 1880:1880
  
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flowerpower
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  backend:
    container_name: ui-backend
    image: dagworks/ui-backend:latest
    ports:
      - "8241:8241"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=user
      - DB_PASSWORD=password # TODO: Change this to a secret
      - HAMILTON_BLOB_STORE=local
      - HAMILTON_ENV=local # local env
      - HAMILTON_LOCAL_BLOB_DIR=/data/blobs # TODO -- set this up to be a better one
      - DJANGO_SECRET_KEY=do_not_use_in_production
      - HAMILTON_TELEMETRY_ENABLED=${HAMILTON_TELEMETRY_ENABLED-true}
      - HAMILTON_AUTH_MODE=permissive
    depends_on:
      - postgres
    volumes:
      - backend_data:/data/

  frontend:
    container_name: ui-frontend
    image: dagworks/ui-frontend:latest
    ports:
      - "8242:8242"
    environment:
      - NGINX_PORT=8242 # NB Custom port won't be visible in console & will mean the backend's shortcut will fail
      - NODE_ENV=development
      - REACT_APP_AUTH_MODE=local
      - REACT_APP_USE_POSTHOG=false
      - REACT_APP_API_URL=http://backend:8241
    depends_on:
      - backend


volumes:
  jupytercode:
  minio_data:
  #minio_config:
  nodered:
  postgres_data:
  backend_data:
