[[libraries]]
  name = "debugging_techniques"
  description = "Synthesized KB for Debugging Techniques from Vertex AI MCP"
  index_file = "debugging_techniques/index.toml"
  last_updated = "2025-04-27"
