name: ewnnesigateway_gdi
job_queue:
  type: rq
  backend:
    type: redis
    uri: null
    username: null
    password: ffGg6X0nUrux
    host: lodl.nes.siemens.de
    port: 6379
    database: 0
    ssl: true
    cert_file: null
    key_file: null
    ca_file: null
    verify_ssl: false
    queues:
    - default
    - high
    - low
    - scheduler
    num_workers: 4
adapter:
  hamilton_tracker:
    username: Lewis
    api_url: https://lodl.nes.siemens.de:8241
    ui_url: https://lodl.nes.siemens.de:8242
    api_key: null
    verify: false
  mlflow:
    tracking_uri: null
    registry_uri: null
    artifact_location: null
  ray:
    ray_init_config: null
    shutdown_ray_on_completion: false
  opentelemetry:
    host: localhost
    port: 6831
