[project]
name = "python-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "flowerpower[io,mqtt,redis,scheduler]>=0.9.12.4",
    "rq>=2.3.2",
    "rq-scheduler>=0.14.0",
]


[tool.uv]
prerelease = "allow"
