global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rq-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - rq-exporter:9726