name: Publish to PyPI

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        rye sync --no-lock
    - name: Build package
      run: |
        rye build --sdist --wheel

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        rye publish --token $PYPI_TOKEN --yes