name: Publish to PyPI

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install UV
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv sync

    - name: Build package
      run: |
        uv build --sdist --wheel

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv publish --token $PYPI_TOKEN